name = "Monsky"
version = "0.1.0"
defaultTargets = ["Monsky"]

[leanOptions]
weak.linter.mathlibStandardSet = true
# weak.linter.flexible = true  # maybe someday enable this

[[lean_lib]]
name = "Monsky"

[[require]]
name = "mathlib"
scope = "leanprover-community"
ref = "v4.25.0-rc2"
